language: python
matrix:
  # This will launch a separate build for each Python version you add
  include:
    - python: 3.6
    - python: 3.7
before_install:
  # Install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  # Create a conda environment from the environment.yml file in this repository
  - echo "$TRAVIS_PYTHON_VERSION"
  - conda env create -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - conda activate advent-code
  - conda list
script:
  # Run the scripts
  - for puz in `ls -d day??/day??_puz?.py; do python ${puz}; done
  # Run tests
  - python -m pytest -v --cov=./
after_success:
  - codecov