name: advent-code
channels:
  - conda-forge
dependencies:
  - codecov
  - coverage
  - flake8
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - seaborn
